// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "title": "Regexplain",
    "description": "Regexplain is a tool that translates regular expressions into plain English."
};
export default messages;