// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "title": "Regexplain",
    "description": "Regexplain is a tool that translates regular expressions into plain English.",
    "validation": {
        "valid": "Valid",
        "invalid": "Invalid",
        "waiting": "Waiting"
    },
    "header": {
        "title": "Regexplain",
        "navigation": {
            "home": "Home",
            "tools": "Tools",
            "about": "About"
        },
        "toggleTheme": "Toggle theme"
    },
    "footer": {
        "title": "Regexplain",
        "copyright": "Copyright © 2025 Nico Möhn - All rights reserved.",
        "github": "GitHub",
        "links": {
            "github": "https://github.com/nitodeco/regexplain"
        }
    },
    "pages": {
        "translation": {
            "input": {
                "title": "Regex",
                "placeholder": "Enter your regex here",
                "button": "Explain"
            },
            "output": {
                "title": "Explanation",
                "placeholder": "Waiting for input...",
                "invalid": "Invalid regex pattern"
            }
        }
    }
};
export default messages;